# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ykwon/CLionProjects/Homework1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ykwon/CLionProjects/Homework1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ykwon/CLionProjects/Homework1/CMakeFiles /home/ykwon/CLionProjects/Homework1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ykwon/CLionProjects/Homework1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pubsubgateway

# Build rule for target.
pubsubgateway: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pubsubgateway
.PHONY : pubsubgateway

# fast build rule for target.
pubsubgateway/fast:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/build
.PHONY : pubsubgateway/fast

#=============================================================================
# Target rules for targets named pubsubserver

# Build rule for target.
pubsubserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pubsubserver
.PHONY : pubsubserver

# fast build rule for target.
pubsubserver/fast:
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/build
.PHONY : pubsubserver/fast

gateway.o: gateway.cpp.o

.PHONY : gateway.o

# target to build an object file
gateway.cpp.o:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/gateway.cpp.o
.PHONY : gateway.cpp.o

gateway.i: gateway.cpp.i

.PHONY : gateway.i

# target to preprocess a source file
gateway.cpp.i:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/gateway.cpp.i
.PHONY : gateway.cpp.i

gateway.s: gateway.cpp.s

.PHONY : gateway.s

# target to generate assembly for a file
gateway.cpp.s:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/gateway.cpp.s
.PHONY : gateway.cpp.s

network.o: network.cpp.o

.PHONY : network.o

# target to build an object file
network.cpp.o:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/network.cpp.o
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/network.cpp.o
.PHONY : network.cpp.o

network.i: network.cpp.i

.PHONY : network.i

# target to preprocess a source file
network.cpp.i:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/network.cpp.i
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/network.cpp.i
.PHONY : network.cpp.i

network.s: network.cpp.s

.PHONY : network.s

# target to generate assembly for a file
network.cpp.s:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/network.cpp.s
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/network.cpp.s
.PHONY : network.cpp.s

pubsub.o: pubsub.cpp.o

.PHONY : pubsub.o

# target to build an object file
pubsub.cpp.o:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/pubsub.cpp.o
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/pubsub.cpp.o
.PHONY : pubsub.cpp.o

pubsub.i: pubsub.cpp.i

.PHONY : pubsub.i

# target to preprocess a source file
pubsub.cpp.i:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/pubsub.cpp.i
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/pubsub.cpp.i
.PHONY : pubsub.cpp.i

pubsub.s: pubsub.cpp.s

.PHONY : pubsub.s

# target to generate assembly for a file
pubsub.cpp.s:
	$(MAKE) -f CMakeFiles/pubsubgateway.dir/build.make CMakeFiles/pubsubgateway.dir/pubsub.cpp.s
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/pubsub.cpp.s
.PHONY : pubsub.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/pubsubserver.dir/build.make CMakeFiles/pubsubserver.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pubsubgateway"
	@echo "... rebuild_cache"
	@echo "... pubsubserver"
	@echo "... gateway.o"
	@echo "... gateway.i"
	@echo "... gateway.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... pubsub.o"
	@echo "... pubsub.i"
	@echo "... pubsub.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

